'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MiniProject.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5a2fe479cc45e43754640849() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5a2fe479cc45e43754640849", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5a2fe479cc45e437546408491() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5a2fe479cc45e437546408491", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to facebook.
        '''</summary>
        Friend ReadOnly Property _String() As String
            Get
                Return ResourceManager.GetString("String", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property abstract_background_with_technology_circuit_board_texture_electronic_motherboard_illustration_communication_and_engineering_concept_illustration_vector1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abstract-background-with-technology-circuit-board-texture-electronic-motherboard-"& _ 
                        "illustration-communication-and-engineering-concept-illustration-vector1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property abstract_background_with_technology_circuit_board_texture_electronic_motherboard_illustration_communication_and_engineering_concept_illustration_vector2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abstract-background-with-technology-circuit-board-texture-electronic-motherboard-"& _ 
                        "illustration-communication-and-engineering-concept-illustration-vector2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property abstract_background_with_technology_circuit_board_texture_electronic_motherboard_illustration_communication_and_engineering_concept_illustration_vector3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abstract-background-with-technology-circuit-board-texture-electronic-motherboard-"& _ 
                        "illustration-communication-and-engineering-concept-illustration-vector3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property abstract_background_with_technology_circuit_board_texture_electronic_motherboard_illustration_communication_and_engineering_concept_illustration_vector4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abstract-background-with-technology-circuit-board-texture-electronic-motherboard-"& _ 
                        "illustration-communication-and-engineering-concept-illustration-vector4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Airpod__2nd_generation_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Airpod (2nd generation)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anonymous_wallpaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anonymous-wallpaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anonymous_wallpaper1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anonymous-wallpaper1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aonic_215_TW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aonic 215 TW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Asus_ROG_Spatha_X() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asus ROG Spatha X", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ayam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ayam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ayam1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ayam1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ayam2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ayam2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Buds2_Pro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buds2 Pro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c870x524() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c870x524", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c870x5241() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c870x5241", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c870x5242() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c870x5242", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c870x5243() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c870x5243", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property earbuds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("earbuds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property earbuds1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("earbuds1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property facebook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facebook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Finalmouse_Starlight_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finalmouse Starlight-12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fit_pro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fit pro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property github_PNG80() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("github_PNG80", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gpu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gpu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gpu1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gpu1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood111() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood111", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood211() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood211", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood311() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood311", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood511() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood511", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood61() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood61", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood611() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood611", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hilltop_hideaway_free_stretch_blog_background_wood7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hilltop-hideaway-free-stretch-blog-background-wood7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hiltop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hiltop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ikki68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ikki68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ikki681() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ikki681", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ikki682() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ikki682", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img_2220() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_2220", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img_22201() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_22201", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img_22202() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_22202", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property key1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property keyboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keyboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property keyboard1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keyboard1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property keycult_no_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keycult no 21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property link() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property link1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property link2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logitech_G502_Hero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logitech G502 Hero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MiniProject() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MiniProject", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Momentum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Momentum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Momentum1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Momentum1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mouse_3_icon__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mouse-3-icon (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property password_icon_png_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("password-icon-png-16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property pexels_photo_10019145() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pexels_photo_10019145", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property promise87() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("promise87", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property promise871() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("promise871", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pulsar_Xlite_V2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pulsar Xlite V2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property qk65() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qk65", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property qk651() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qk651", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Quantum_TWS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Quantum TWS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QuietComfort() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuietComfort", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QuietComfort1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuietComfort1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Razer_Basilisk_Ultimate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Razer Basilisk Ultimate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Razer_Basilisk_V3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Razer Basilisk V3 ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Razer_Deathadder_V2_Pro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Razer Deathadder V2 Pro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property razer_mercury_OGimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("razer-mercury-OGimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property razer_mercury_OGimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("razer-mercury-OGimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Razer_Naga_pro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Razer Naga pro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Razer_Viper_Ultimate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Razer Viper Ultimate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Razer_Viper_V2_Pro_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Razer Viper V2 Pro ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rtx_3060() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtx 3060", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rtx_3060_ti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtx 3060 ti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rtx_3070() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtx 3070", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rtx_3070_ti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtx 3070 ti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rtx_3080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtx 3080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rtx_3080_ti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtx 3080 ti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rtx_3090() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtx 3090", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rtx_3090_ti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtx 3090 ti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rtx_4090_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtx 4090 ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tgr_jane_ce() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tgr jane ce", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tgr_jane_me() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tgr jane me", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tgr_police() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tgr police", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property th() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("th", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property th1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("th1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tiger80() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tiger80", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tiger801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tiger801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_Profile_PNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User-Profile-PNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WF_1000XM4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WF-1000XM4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wp2592437() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wp2592437", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wp25924371() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wp25924371", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wp6977321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wp6977321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wp69773211() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wp69773211", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wp6977459() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wp6977459", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wp69774591() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wp69774591", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property X() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("X", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property X1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("X1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property X2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("X2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property X3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("X3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zoom65() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom65", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zoom651() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom651", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
